services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: back
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
        - backGamesloc:/var/lib/postgresql/data
        - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - gamesloc
  
  spring:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8080:8080"  
    networks:
      - gamesloc
  angular:
    build:
      context: ../front-gamesloc
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - gamesloc
volumes:
  backGamesloc:
networks:
  gamesloc:
    driver: bridge
